{% set name = "neocmakelsp" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Decodetalkers/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 23d2fd6f6bd0152dad9b6bdf9b5d6932d97ccd106bfb47d6d6fee563ea5a7eec

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/Decodetalkers/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Another cmake lsp
  dev_url: https://github.com/Decodetalkers/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
