{% set name = "neocmakelsp" %}
{% set version = "0.8.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Decodetalkers/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: de00f241038ac64ce3149ff9529791517e7ea4f106e37ee88b0bbac9c7cb42e4

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/Decodetalkers/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Another cmake lsp
  dev_url: https://github.com/Decodetalkers/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
