{% set name = "neocmakelsp" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Decodetalkers/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cf395c16d14d16ad54deda0fc6d2e9f1160163417c716ad18030e611947f9600

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/Decodetalkers/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Another cmake lsp
  dev_url: https://github.com/Decodetalkers/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
