context:
  version: "0.10.0"

package:
  name: neocmakelsp
  version: ${{ version }}

source:
  url: https://github.com/Decodetalkers/neocmakelsp/archive/v${{ version }}.tar.gz
  sha256: 084f4e8605e0834c3ca85abd7460801dc22454f45f68557340d02642a4be3c72

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - neocmakelsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Another cmake lsp
  homepage: https://github.com/Decodetalkers/neocmakelsp
  repository: https://github.com/Decodetalkers/neocmakelsp

extra:
  recipe-maintainers:
    - danielnachun
