context:
  version: "0.8.16"

package:
  name: neocmakelsp
  version: ${{ version }}

source:
  url: https://github.com/Decodetalkers/neocmakelsp/archive/v${{ version }}.tar.gz
  sha256: fd533468e0ab23977243d4923715dc010ddd9d299f8a3d21c1252cfc1ee009b9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - neocmakelsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Another cmake lsp
  homepage: https://github.com/Decodetalkers/neocmakelsp
  repository: https://github.com/Decodetalkers/neocmakelsp

extra:
  recipe-maintainers:
    - danielnachun
