context:
  version: "0.9.0"

package:
  name: neocmakelsp
  version: ${{ version }}

source:
  url: https://github.com/Decodetalkers/neocmakelsp/archive/v${{ version }}.tar.gz
  sha256: 11aa287b4bfaf60de65b13610656b0dca0ede24881b3a03465a569d15a6be0ca

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - neocmakelsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Another cmake lsp
  homepage: https://github.com/Decodetalkers/neocmakelsp
  repository: https://github.com/Decodetalkers/neocmakelsp

extra:
  recipe-maintainers:
    - danielnachun
