context:
  version: "0.11.2"

package:
  name: neocmakelsp
  version: ${{ version }}

source:
  url: https://github.com/Decodetalkers/neocmakelsp/archive/v${{ version }}.tar.gz
  sha256: eb88d467816f67c22cfa864f3d3ecc4eb5cfbc1afa018fac61a23915f21745e6

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - neocmakelsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Another cmake lsp
  homepage: https://github.com/Decodetalkers/neocmakelsp
  repository: https://github.com/Decodetalkers/neocmakelsp

extra:
  recipe-maintainers:
    - danielnachun
