context:
  version: "0.8.26"

package:
  name: neocmakelsp
  version: ${{ version }}

source:
  url: https://github.com/Decodetalkers/neocmakelsp/archive/v${{ version }}.tar.gz
  sha256: a400e86420cc7d67008a2139c3d7d9853b2775ffb5b6c53964775ffb505e5a36

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - neocmakelsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Another cmake lsp
  homepage: https://github.com/Decodetalkers/neocmakelsp
  repository: https://github.com/Decodetalkers/neocmakelsp

extra:
  recipe-maintainers:
    - danielnachun
